-- MOSTRAR LOS NOMBRES DE TODOS LOS USUARIOS QUE PERTECEN A CHILE

SELECT C.CUSTOMER_id CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, CI.CITY, CO.COUNTRY FROM CUSTOMER C
JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID
JOIN CITY CI
ON A.CITY_ID = CI.CITY_ID
JOIN COUNTRY CO
ON CI.COUNTRY_ID = CO.COUNTRY_ID
WHERE CO.COUNTRY ILIKE '%Chile%';

--PAISES RELACIONADOS CON CIUDAD

SELECT CO.COUNTRY, COUNT(*) FROM COUNTRY CO
LEFT JOIN CITY CI
ON CI.COUNTRY_ID = CO.COUNTRY_ID
GROUP BY CO.COUNTRY
ORDER BY COUNT(*) DESC;



SELECT * FROM CUSTOMER ORDER BY CUSTOMER_ID LIMIT 9 OFFSET 18;

-- EJEMPLO DE SUBCONSULTA




SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, COUNT(*) CANTIDAD_RENTAL FROM RENTAL R
JOIN CUSTOMER C
ON R.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID 
IN (
	SELECT C.CUSTOMER_id FROM CUSTOMER C
	JOIN ADDRESS A
	ON C.ADDRESS_ID = A.ADDRESS_ID
	JOIN CITY CI
	ON A.CITY_ID = CI.CITY_ID
	JOIN COUNTRY CO
	ON CI.COUNTRY_ID = CO.COUNTRY_ID
	WHERE CO.COUNTRY ILIKE '%Chile%'
)
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY C.FIRST_NAME ASC;

-- CUÁNTAS PELÍCULAS EXISTEN POR CATEGORÍA

SELECT C.CATEGORY_ID, C.NAME, COUNT(*) CANTIDAD FROM CATEGORY C
JOIN FILM_CATEGORY FC
ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN FILM F
ON F.FILM_ID = FC.FILM_ID
GROUP BY C.CATEGORY_ID, C.NAME
ORDER BY COUNT(*) DESC;


-- CASE

SELECT product_name,
CASE
  WHEN price < 10 THEN 'Low price product'
  WHEN price > 50 THEN 'High price product'
ELSE
  'Normal product'
END
FROM products;


-- CORTOMETRAJE -> HASTA 50 MINUTOS Y MAYOR A ESO LARGOMETRAJE
SELECT title, length,
CASE
	WHEN length <= 50 THEN 'cortometraje'
ELSE
	'largometraje'
END AS detalle
FROM FILM


-- SUBCONSULTAS
SELECT detalle, count(*) FROM 
(SELECT title, length,
CASE
	WHEN length <= 50 THEN 'cortometraje'
ELSE
	'largometraje'
END AS detalle
FROM FILM) data_temp
GROUP BY detalle;


SELECT COUNT(*) FROM FILM WHERE LENGTH <= 50;




SELECT *,
CASE
	WHEN CANTIDAD_RENTAL >= 30 THEN 'Cliente VIP'
	WHEN CANTIDAD_RENTAL <= 20 THEN 'Cliente por definir'
ELSE
	'Cliente normal'
END AS tipo_cliente
FROM 
(SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, COUNT(*) CANTIDAD_RENTAL FROM RENTAL R
JOIN CUSTOMER C
ON R.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID 
IN (
	SELECT C.CUSTOMER_id FROM CUSTOMER C
	JOIN ADDRESS A
	ON C.ADDRESS_ID = A.ADDRESS_ID
	JOIN CITY CI
	ON A.CITY_ID = CI.CITY_ID
	JOIN COUNTRY CO
	ON CI.COUNTRY_ID = CO.COUNTRY_ID
)
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
ORDER BY C.FIRST_NAME ASC) DATA_TEMP;


-- SUBCONSULTAS A NIVEL WHERE

SELECT * FROM FILM WHERE language_id IN(
	SELECT language_id FROM LANGUAGE WHERE name IN('English', 'French', 'German')
)
ORDER BY language_id DESC;


SELECT language_id FROM FILM
GROUP BY language_id;


SELECT * FROM STORE WHERE store_id IN (
	SELECT store_id FROM inventory i
	JOIN film f
	ON f.film_id = i.film_id
	WHERE f.title ILIKE 'Amistad Midsummer'
	GROUP BY store_id
);


SELECT title FROM film;


 
SELECT * FROM SALES_BY_FILM_CATEGORY
order by total_sales DESC;
 